services:

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEBUI_NAME=${WEBUI_NAME}
      - RAG_EMBEDDING_ENGINE=openai
      - RAG_EMBEDDING_MODEL=text-embedding-3-small
    volumes:
      - open-webui:/app/backend/data
    networks:
      - isolated
      - internet

  pipelines:
    container_name: pipelines
    image: ghcr.io/open-webui/pipelines:main
    depends_on:
      - open-webui
    restart: unless-stopped
    volumes:
      - pipelines:/app/pipelines
    networks:
      - isolated
      - internet

  nginx:
    container_name: nginx
    ports:
      - 80:80
      - 443:443 
    image: nginx:latest
    depends_on:
      - open-webui
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - isolated
      - internet

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  isolated:
    driver: bridge
    internal: true
  internet:
    driver: bridge

volumes:
  open-webui: {}
  pipelines: {}