services:

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama 
    networks:
      - isolated
      - internet
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    depends_on:
      - ollama
    restart: unless-stopped
    environment:
      - 'RAG_EMBEDDING_MODEL_AUTO_UPDATE=true'
      - 'ENABLE_SIGNUP=false'
      - 'WEBUI_AUTH=false'
      - 'DEFAULT_MODELS=gpt-4o'
      - 'OPENAI_API_KEY='
      - 'WEBUI_NAME=LLM for BASS'
      - 'ENABLE_RAG_HYBRID_SEARCH=true'
      - 'RAG_EMBEDDING_ENGINE=ollama'
      - 'RAG_EMBEDDING_MODEL=nomic-embed-text:latest'
      - 'RAG_RERANKING_MODEL=mixedbread-ai/mxbai-rerank-base-v1'
      - 'RAG_TOP_K=10'
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WHISPER_MODEL=small'
    volumes:
      - open-webui:/app/backend/data
    networks:
      - isolated
      - internet

  pipelines:
    container_name: pipelines
    image: ghcr.io/open-webui/pipelines:main
    depends_on:
      - open-webui
    restart: unless-stopped
    volumes:
      - pipelines:/app/pipelines
    networks:
      - isolated
      - internet

  nginx:
    container_name: nginx
    ports:
      - "80:80"
    image: nginx:latest
    depends_on:
      - open-webui
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - isolated
      - internet

networks:
  isolated:
    driver: bridge
    internal: true
  internet:
    driver: bridge

volumes:
  open-webui: {}
  pipelines: {}
  ollama: {}