services:

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEBUI_NAME=${WEBUI_NAME}
      - 'RAG_EMBEDDING_ENGINE=openai'
      - 'RAG_EMBEDDING_MODEL=text-embedding-3-small'
    volumes:
      - open-webui:/app/backend/data
    networks:
      - isolated
      - internet

  nginx:
    container_name: nginx
    ports:
      - "80:80"
    image: nginx:latest
    depends_on:
      - open-webui
    restart: unless-stopped
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - isolated
      - internet

networks:
  isolated:
    driver: bridge
    internal: true
  internet:
    driver: bridge

volumes:
  open-webui: {}
  pipelines: {}